service: aws-sandbox-serverless

useDotenv: true

disabledDeprecations:
  - OUTDATED_NODEJS

plugins:
  - serverless-python-requirements
  - serverless-wsgi
  - serverless-dynamodb-local
  - serverless-offline
provider:
  name: aws
  runtime: python3.9
  memorySize: ${self:custom.memorySize}
  timeout: ${self:custom.timeout}
  stage: ${opt:stage, 'production'}
  region: ${opt:region, 'us-east-1'}
  stackName: ${self:service}-${self:provider.stage}
  apiName: ${self:service}-${self:provider.stage}
  stackTags:
    Name: ${self:provider.stackName}
    environment: ${self:provider.stage}
    role: serverless
    repo: aws-sandbox-serverless
    team: developers
  # profile: ${opt:profile, 'production-dmitry_rendov'}
  iam:
    role: ${self:custom.sls_role}
  deploymentBucket:
    name: ${opt:bucket, 'sb-production-serverless-6e9141321b09'}
    serverSideEncryption: AES256
    tags:
      env: ${self:provider.stage}
  environment:
    REGION: ${self:provider.region}
    SERVICE_NAME: ${self:service}
    # AWS_PROFILE: ${opt:profile, 'sts'}
    TESTS_TABLE: 'tests-table-${self:provider.stage}'
    WEB_PATH: 'src/web/app.app'

custom: ${file(./sls/env/${self:provider.stage}.yml)}

package:
  individually: true
  excludeDevDependencies: true
  patterns:
    - 'src/**'
    - '!__pycache__/'
    - '!node_modules'
    - '!README.md'
    - '!LICENSE'
    - '!serverless.yml'
    - '!package-lock.json'
    - '!src/web/artefacts/'
    - '!sls/*'
    - '!sls/env/*'

resources:
  - ${file(./sls/resources.yml)}

functions:
  - ${file(./sls/functions.yml)}
